/** 50 unique costumes — images fetched via Google "<name> cosplay" search. */
export const COSTUME_CATALOG = [
  { slug: "raiden-shogun", name: "Raiden Shogun", category: "Anime & Gaming", theme: "Genshin Impact", gender: "Women", size: "M" },
  { slug: "spider-man-miles", name: "Spider-Man Miles Morales", category: "Superheroes", theme: "Marvel", gender: "Unisex", size: "L" },
  { slug: "medieval-knight", name: "Medieval Knight Armor", category: "Historical & Fantasy", theme: "Medieval", gender: "Men", size: "XL" },
  { slug: "sailor-moon", name: "Sailor Moon", category: "Anime & Gaming", theme: "Sailor Moon", gender: "Women", size: "S" },
  { slug: "iron-man-mk50", name: "Iron Man MK50", category: "Superheroes", theme: "Marvel", gender: "Men", size: "L" },
  { slug: "elsa-frozen", name: "Elsa Frozen", category: "Movies & TV", theme: "Disney", gender: "Women", size: "M" },
  { slug: "naruto-hokage", name: "Naruto Hokage", category: "Anime & Gaming", theme: "Naruto", gender: "Unisex", size: "M" },
  { slug: "wonder-woman", name: "Wonder Woman", category: "Superheroes", theme: "DC", gender: "Women", size: "M" },
  { slug: "demon-slayer-tanjiro", name: "Demon Slayer Tanjiro", category: "Anime & Gaming", theme: "Demon Slayer", gender: "Men", size: "L" },
  { slug: "wednesday-addams", name: "Wednesday Addams", category: "Movies & TV", theme: "Wednesday", gender: "Women", size: "S" },
  { slug: "batman-dark-knight", name: "Batman Dark Knight", category: "Superheroes", theme: "DC", gender: "Men", size: "XL" },
  { slug: "mikasa-ackerman", name: "Mikasa Ackerman", category: "Anime & Gaming", theme: "Attack on Titan", gender: "Women", size: "M" },
  { slug: "harry-potter-robes", name: "Harry Potter Robes", category: "Movies & TV", theme: "Harry Potter", gender: "Unisex", size: "M" },
  { slug: "captain-america", name: "Captain America", category: "Superheroes", theme: "Marvel", gender: "Men", size: "L" },
  { slug: "hatsune-miku", name: "Hatsune Miku", category: "Anime & Gaming", theme: "Vocaloid", gender: "Women", size: "S" },
  { slug: "witch-classic", name: "Witch Classic", category: "Horror & Halloween", theme: "Halloween", gender: "Women", size: "M" },
  { slug: "vampire-lord", name: "Vampire Lord", category: "Horror & Halloween", theme: "Gothic", gender: "Unisex", size: "L" },
  { slug: "samurai-warrior", name: "Samurai Warrior", category: "Historical & Fantasy", theme: "Feudal Japan", gender: "Men", size: "L" },
  { slug: "princess-peach", name: "Princess Peach", category: "Anime & Gaming", theme: "Mario", gender: "Women", size: "M" },
  { slug: "link-zelda", name: "Link Zelda", category: "Anime & Gaming", theme: "Zelda", gender: "Unisex", size: "M" },
  { slug: "black-panther", name: "Black Panther", category: "Superheroes", theme: "Marvel", gender: "Men", size: "L" },
  { slug: "cinderella-gown", name: "Cinderella Ball Gown", category: "Movies & TV", theme: "Disney", gender: "Women", size: "S" },
  { slug: "joker-classic", name: "Joker Classic", category: "Superheroes", theme: "DC", gender: "Men", size: "L" },
  { slug: "pikachu-onesie", name: "Pikachu Onesie", category: "Anime & Gaming", theme: "Pokemon", gender: "Unisex", size: "M" },
  { slug: "mandalorian-armor", name: "Mandalorian Armor", category: "Movies & TV", theme: "Star Wars", gender: "Unisex", size: "L" },
  { slug: "deadpool-merc", name: "Deadpool Mercenary", category: "Superheroes", theme: "Marvel", gender: "Men", size: "L" },
  { slug: "harley-quinn", name: "Harley Quinn", category: "Superheroes", theme: "DC", gender: "Women", size: "M" },
  { slug: "nezuko-demon-slayer", name: "Nezuko Demon Slayer", category: "Anime & Gaming", theme: "Demon Slayer", gender: "Women", size: "S" },
  { slug: "goku-saiyan", name: "Goku Saiyan", category: "Anime & Gaming", theme: "Dragon Ball", gender: "Men", size: "L" },
  { slug: "levi-ackerman", name: "Levi Ackerman", category: "Anime & Gaming", theme: "Attack on Titan", gender: "Men", size: "M" },
  { slug: "belle-beauty-beast", name: "Belle Beauty and the Beast", category: "Movies & TV", theme: "Disney", gender: "Women", size: "M" },
  { slug: "ariel-mermaid", name: "Ariel Mermaid", category: "Movies & TV", theme: "Disney", gender: "Women", size: "S" },
  { slug: "moana-wayfinder", name: "Moana Wayfinder", category: "Movies & TV", theme: "Disney", gender: "Women", size: "M" },
  { slug: "thor-asgardian", name: "Thor Asgardian", category: "Superheroes", theme: "Marvel", gender: "Men", size: "XL" },
  { slug: "scarlet-witch", name: "Scarlet Witch", category: "Superheroes", theme: "Marvel", gender: "Women", size: "M" },
  { slug: "flash-speedster", name: "The Flash Speedster", category: "Superheroes", theme: "DC", gender: "Men", size: "L" },
  { slug: "supergirl-krypton", name: "Supergirl Kryptonian", category: "Superheroes", theme: "DC", gender: "Women", size: "M" },
  { slug: "ghostface-scream", name: "Ghostface Scream", category: "Horror & Halloween", theme: "Horror", gender: "Unisex", size: "L" },
  { slug: "skeleton-reaper", name: "Grim Reaper Skeleton", category: "Horror & Halloween", theme: "Halloween", gender: "Unisex", size: "L" },
  { slug: "pirate-captain", name: "Pirate Captain", category: "Historical & Fantasy", theme: "Pirate", gender: "Unisex", size: "L" },
  { slug: "viking-warrior", name: "Viking Warrior", category: "Historical & Fantasy", theme: "Viking", gender: "Men", size: "XL" },
  { slug: "roman-centurion", name: "Roman Centurion", category: "Historical & Fantasy", theme: "Ancient Rome", gender: "Men", size: "L" },
  { slug: "renaissance-noble", name: "Renaissance Noble", category: "Historical & Fantasy", theme: "Renaissance", gender: "Unisex", size: "M" },
  { slug: "steampunk-inventor", name: "Steampunk Inventor", category: "Sci-Fi", theme: "Steampunk", gender: "Unisex", size: "L" },
  { slug: "astronaut-explorer", name: "Astronaut Explorer", category: "Sci-Fi", theme: "Space", gender: "Unisex", size: "L" },
  { slug: "cyberpunk-hacker", name: "Cyberpunk Hacker", category: "Sci-Fi", theme: "Cyberpunk", gender: "Unisex", size: "M" },
  { slug: "alien-xenomorph", name: "Alien Xenomorph", category: "Sci-Fi", theme: "Alien", gender: "Unisex", size: "L" },
  { slug: "ballerina-nutcracker", name: "Ballerina Nutcracker", category: "Theatrical", theme: "Ballet", gender: "Women", size: "S" },
  { slug: "mozart-classical", name: "Mozart Classical", category: "Theatrical", theme: "Classical", gender: "Men", size: "M" },
  { slug: "circus-ringmaster", name: "Circus Ringmaster", category: "Theatrical", theme: "Circus", gender: "Unisex", size: "L" },
];
